version: "3.8"
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE : chgmanager
      MONGO_INITDB_ROOT_USERNAME : root
      MONGO_INITDB_ROOT_PASSWORD : example
    volumes:
      - ./db/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    logging:
      driver: none
  app:
    build: ./app
    container_name: app
    restart: always
    environment:
      APPINSIGHTS_INSTRUMENTATIONKEY : a7d12fbc-299f-4be1-b68e-4e4ed44dcb6c
      dbServer : db
      dbName : chgmanager
      dbUser : root
      dbPass : example
    ports:
      - "80:80"
  dbadmin:
    image: mongo-express
    container_name: dbadmin
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    logging:
      driver: none